mqtt:
  url: $MQTT_HOST$
  port: 8883
  username: mqtt
  password: mqtt
  client_id: client
time_series:
  url: $INFLUXDB_HOST$
  port: 8884
  username: integration-test-user
  password: the-giant-pink-unicorn
  bucket_name: time_series
things:
  - name: Washing machine
    type: washing_machine
    sources:
      - mqtt_topic: measurements/home/indoor/washing_machine/power
        type: consumption
      - mqtt_topic: home/things/washing_machine/load
        type: loading
      - mqtt_topic: home/things/washing_machine/unload
        type: unloading
    destinations:
      planned_notifications:
        - mqtt_topic: home/things/washing_machine
          cron_expression: '* * * * *'
  - name: Dishwasher
    type: dishwasher
    run_complete_when:
      below_threshold_for: 1
      threshold: 10
    sources:
      - mqtt_topic: measurements/home/indoor/dishwasher/power
        type: consumption
      - mqtt_topic: home/things/dishwasher/load
        type: loading
      - mqtt_topic: home/things/dishwasher/unload
        type: unloading
    destinations:
      planned_notifications:
        - mqtt_topic: things/dishwasher
          cron_expression: '* * * * *'
  - name: Dryer
    type: dryer
    sources:
      - mqtt_topic: zigbee/home/indoor/dryer
        type: consumption
      - mqtt_topic: home/things/dryer/load
        type: loading
      - mqtt_topic: home/things/dryer/unload
        type: unloading
    destinations:
      planned_notifications:
        - mqtt_topic: home/things/robot-cleaner
          cron_expression: '* * * * * */30'
  - name: Washer Kai
    type: washing_machine
    sources:
      - mqtt_topic: measurements/home/indoor/washing_machine_kai/power
        type: consumption
      - mqtt_topic: home/things/washing_machine_kai/load
        type: loading
      - mqtt_topic: home/things/washing_machine_kai/unload
        type: unloading
    destinations:
      planned_notifications:
        - mqtt_topic: home/things/washing_machine_kai
          cron_expression: '* * * * *'
  - name: Parents bedroom
    type: room
    temperature_thresholds:
      optimal:
        lower: 19
        upper: 22
      critical_lower: 16
      critical_upper: 28
    humidity_thresholds:
      optimal:
        lower: 40
        upper: 60
      critical_lower: 30
      critical_upper: 75
    sources:
      - mqtt_topic: zigbee/home/parents-bedroom/sensor01
        measures:
          - type: temperature
            path: $.temperature
          - type: humidity
            path: $.humidity
    destinations:
      planned_notifications:
        - mqtt_topic: home/rooms/parents-bedroom
          cron_expression: '* * * * *'
  - name: Hallway
    type: room
    temperature_thresholds:
      optimal:
        lower: 20
        upper: 23
      critical_lower: 15
      critical_upper: 30
    humidity_thresholds:
      optimal:
        lower: 50
        upper: 75
      critical_lower: 40
      critical_upper: 85
    sources:
      - mqtt_topic: zigbee/home/hallway/sensor01
        measures:
          - type: temperature
            path: $.temperature
          - type: humidity
            path: $.humidity
    destinations:
      planned_notifications:
        - mqtt_topic: home/rooms/hallway
          cron_expression: '* * * * *'
  - name: Bathroom
    type: room
    temperature_thresholds:
      optimal:
        lower: 21
        upper: 24
      critical_lower: 19
      critical_upper: 30
    humidity_thresholds:
      optimal:
        lower: 50
        upper: 70
      critical_lower: 40
      critical_upper: 85
    sources:
      - mqtt_topic: zigbee/home/bathroom/sensor01
        measures:
          - type: temperature
            path: $.temperature
          - type: humidity
            path: $.humidity
    destinations:
      planned_notifications:
        - mqtt_topic: home/rooms/bathroom
          cron_expression: '* * * * *'
  - name: Kitchen
    type: room
    temperature_thresholds:
      optimal:
        lower: 18
        upper: 22
      critical_lower: 16
      critical_upper: 30
    humidity_thresholds:
      optimal:
        lower: 50
        upper: 60
      critical_lower: 40
      critical_upper: 80
    sources:
      - mqtt_topic: zigbee/home/kitchen/sensor01
        measures:
          - type: temperature
            path: $.temperature
          - type: humidity
            path: $.humidity
    destinations:
      planned_notifications:
        - mqtt_topic: home/rooms/kitchen
          cron_expression: '* * * * *'
  - name: Living room
    type: room
    temperature_thresholds:
      optimal:
        lower: 20
        upper: 22
      critical_lower: 18
      critical_upper: 30
    humidity_thresholds:
      optimal:
        lower: 40
        upper: 60
      critical_lower: 30
      critical_upper: 70
    sources:
      - mqtt_topic: zigbee/home/living-room/sensor01
        measures:
          - type: temperature
            path: $.temperature
          - type: humidity
            path: $.humidity
    destinations:
      planned_notifications:
        - mqtt_topic: home/rooms/living-room
          cron_expression: '* * * * *'
  - name: Terrace
    type: room
    temperature_thresholds:
      optimal:
        lower: 15
        upper: 23
      critical_lower: 6
      critical_upper: 30
    humidity_thresholds:
      optimal:
        lower: 40
        upper: 70
      critical_lower: 30
      critical_upper: 80
    sources:
      - mqtt_topic: zigbee/home/terrace/sensor01
        measures:
          - type: temperature
            path: $.temperature
          - type: humidity
            path: $.humidity
    destinations:
      planned_notifications:
        - mqtt_topic: home/rooms/terrace
          cron_expression: '* * * * *'
  - name: Ash
    type: person
    sources:
      - application: calendar
        name: Ash Private
        url: http://$CALDAV_HOST$:9086/billy/ash--ash-private
        username: billy
        password: secret12112
        update_cron: "* * * * * 0/5"
        color_hex: f439c4
    destinations:
      planned_notifications:
        - mqtt_topic: persons/ash/appointments
          subject: daily-appointments
          cron_expression: "* * * * * 0/30"
  - name: Robin
    type: person
    sources:
      - application: calendar
        name: Robin Private
        url: http://$CALDAV_HOST$:9086/billy/robin--robin-private
        username: billy
        password: secret12112
        update_cron: "* * * * * 0/5"
        color_hex: f439c4
    destinations:
      planned_notifications:
        - mqtt_topic: persons/billy/appointments
          subject: daily-appointments
          cron_expression: "* * * * * 0/30"
  - name: Billy
    type: person
    sources:
      - application: calendar
        name: Billy Private
        url: http://$CALDAV_HOST$:9086/billy/billy--billy-private
        username: billy
        password: secret12112
        update_cron: "* * * * * 0/5"
        color_hex: f439c4
    destinations:
      planned_notifications:
        - mqtt_topic: persons/billy/appointments
          subject: daily-appointments
          cron_expression: "* * * * * 0/30"
flaskr:
  HOST: 0.0.0.0
  PORT: 8080